# Generated by Django 2.1.3 on 2018-12-17 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drego', '0002_auto_20181216_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('level', models.CharField(choices=[(1, 'Pro'), (2, 'Platinum'), (3, 'Pick of the week')], default=1, max_length=20)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='plans',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='drego.Plan'),
        ),
    ]
